Tweaks 8

diff --git a/.azure/macos-build-pipeline.yml b/.azure/macos-build-pipeline.yml
--- a/.azure/macos-build-pipeline.yml
+++ b/.azure/macos-build-pipeline.yml
@@ -67,6 +67,60 @@ steps:
     actions: 'build'
     configuration: 'Release'
     sdk: 'macosx'
-    xcWorkspacePath: 'build/warzone2100.xcodeproj'
+    xcWorkspacePath: '$(Pipeline.Workspace)/build/warzone2100.xcodeproj'
     scheme: 'warzone2100'
     packageApp: false
+- task: CmdLine@2
+  displayName: Output build info
+  inputs:
+    script: |
+      cd "${AGENT_BUILDDIRECTORY}"
+      
+      # Verify "warzone2100.zip" was created
+      BUILT_WARZONE_ZIP="build/warzone2100.zip"
+      if [ ! -f "${BUILT_WARZONE_ZIP}" ]; then
+        echo "ERROR: Something went wrong, and \"${BUILT_WARZONE_ZIP}\" does not exist"
+        exit 1
+      fi
+      # Extract & verify the .zip contents
+      TMP_PKG_EXTRACT_DIR="build/tmp/_wzextract"
+      rm -rf "${TMP_PKG_EXTRACT_DIR}"
+      if [ ! -d "${TMP_PKG_EXTRACT_DIR}" ]; then
+        mkdir -p "${TMP_PKG_EXTRACT_DIR}"
+      fi
+      unzip -qq "${BUILT_WARZONE_ZIP}" -d "${TMP_PKG_EXTRACT_DIR}"
+      cd "${TMP_PKG_EXTRACT_DIR}"
+      if [ ! -d "Warzone 2100.app" ]; then
+        echo "ERROR: \"Warzone 2100.app\" was not extracted from \"${BUILT_WARZONE_ZIP}\""
+        exit 1
+      fi
+      # For debugging purposes, output some information about the generated "Warzone 2100.app" (inside the .zip)
+      echo "Generated \"Warzone 2100.app\""
+      generated_infoplist_location="Warzone 2100.app/Contents/Info.plist"
+      generated_versionnumber=$(/usr/libexec/PlistBuddy -c "Print CFBundleShortVersionString" "${generated_infoplist_location}")
+      echo "  -> Version Number (CFBundleShortVersionString): ${generated_versionnumber}"
+      generated_buildnumber=$(/usr/libexec/PlistBuddy -c "Print CFBundleVersion" "${generated_infoplist_location}")
+      echo "  -> Build Number (CFBundleVersion): ${generated_buildnumber}"
+      generated_minimumsystemversion=$(/usr/libexec/PlistBuddy -c "Print LSMinimumSystemVersion" "${generated_infoplist_location}")
+      echo "  -> Minimum macOS (LSMinimumSystemVersion): ${generated_minimumsystemversion}"
+      codesign_verify_result=$(codesign --verify --deep --strict --verbose=2 "Warzone 2100.app" 2>&1)
+      echo "  -> codesign --verify --deep --strict --verbose=2 \"Warzone 2100.app\""
+      if [ -n "${codesign_verify_result}" ]; then
+        while read -r line; do
+          echo "     $line"
+        done <<< "$codesign_verify_result"
+      else
+        echo "     (No output?)"
+      fi
+      cd - > /dev/null
+      
+      echo "Generated warzone2100.zip: \"${BUILT_WARZONE_ZIP}\""
+      ZIP_HASH="$(shasum -a 512 "${BUILT_WARZONE_ZIP}")"
+      ZIP_SIZE="$(stat -f '%z' "${BUILT_WARZONE_ZIP}")"
+      echo "  -> SHA512: ${ZIP_HASH}"
+      echo "  -> Size (bytes): ${ZIP_SIZE}"
+- task: PublishPipelineArtifact@1
+  inputs:
+    targetPath: '$(Pipeline.Workspace)/build/warzone2100.zip'
+    artifact: 'warzone2100_macOS.zip'
+    publishLocation: 'pipeline'
