Tweak 10

diff --git a/.azure/macos-build-pipeline.yml b/.azure/macos-build-pipeline.yml
--- a/.azure/macos-build-pipeline.yml
+++ b/.azure/macos-build-pipeline.yml
@@ -75,6 +75,10 @@ steps:
   inputs:
     script: |
       cd "${AGENT_BUILDDIRECTORY}"
+      echo "BUILD_ARTIFACTSTAGINGDIRECTORY=${BUILD_ARTIFACTSTAGINGDIRECTORY}"
+      OUTPUT_DIR="${BUILD_ARTIFACTSTAGINGDIRECTORY}"
+      
+      cat "src/autorevision.h"
       
       # Verify "warzone2100.zip" was created
       BUILT_WARZONE_ZIP="build/warzone2100.zip"
@@ -114,13 +118,20 @@ steps:
       fi
       cd - > /dev/null
       
-      echo "Generated warzone2100.zip: \"${BUILT_WARZONE_ZIP}\""
-      ZIP_HASH="$(shasum -a 512 "${BUILT_WARZONE_ZIP}")"
-      ZIP_SIZE="$(stat -f '%z' "${BUILT_WARZONE_ZIP}")"
+      # Move warzone2100.zip to the output directory, renaming it
+      DESIRED_ZIP_NAME="warzone2100_macOS.zip"
+      mv "$BUILT_WARZONE_ZIP" "${OUTPUT_DIR}/${DESIRED_ZIP_NAME}"
+      result=${?}
+      if [ $result -ne 0 ]; then
+        echo "ERROR: Failed to move zip file"
+        exit ${result}
+      fi
+      echo "Generated warzone2100.zip: \"${OUTPUT_DIR}/${DESIRED_ZIP_NAME}\""
+      ZIP_HASH="$(shasum -a 512 "${OUTPUT_DIR}/${DESIRED_ZIP_NAME}")"
+      ZIP_SIZE="$(stat -f '%z' "${OUTPUT_DIR}/${DESIRED_ZIP_NAME}")"
       echo "  -> SHA512: ${ZIP_HASH}"
       echo "  -> Size (bytes): ${ZIP_SIZE}"
 - task: PublishPipelineArtifact@1
   inputs:
-    targetPath: '$(Pipeline.Workspace)/build/warzone2100.zip'
-    artifact: 'warzone2100_macOS.zip'
-    publishLocation: 'pipeline'
+    targetPath: '$(Build.ArtifactStagingDirectory)'
+    artifact: 'warzone2100_macOS'
